language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y byacc
  - scripts/downloadRelease.sh fregec.jar

before_script:
  - mkdir -p build dist doc

script:
  - make compiler1 || true   # until issue#100 is fixed
  - make runtime compiler fregec.jar dist && java -cp fregec.jar frege.tools.Quick -v fregec.jar
